## パッケージのインストール
FROM node:18-alpine as desp-stage
WORKDIR /app

COPY ./package.json ./package-lock.json ./
RUN npm install

## buildを実行
FROM oven/bun:alpine as build-stage

WORKDIR /work

COPY --from=desp-stage /app/node_modules ./work/node_modules
COPY . /work/

## runtime環境を作成
FROM oven/bun:alpine as runtime-stage

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

WORKDIR /app

COPY ./package.json ./package-lock.json ./
COPY --from=desp-stage /app/node_modules ./work/node_modules
COPY --from=build-stage /work/src ./src

EXPOSE 3000

ENV NODE_ENV prod

CMD ["bun", "run","dev"]