run:
	bun run dev
migrate:
	bun prisma migrate dev --name init
db_pull:
	bun prisma db pull
db_push:
	bun prisma db push
db_deploy:
	bun prisma migrate deploy
up:
	docker compose up
down:
	docker compose down